### ISSUE TITLE
Error start node-red on docker with node-red-contrib-zeebe

### ISSUE THREAD

**Issue by lucasgiusti** [camunda-community-hub/node-red-contrib-zeebe#110]
Dockerfile:
`FROM nodered/node-red

COPY package.json .
RUN npm install --only=production

COPY settings.js /data/settings.js
COPY flows.json /data/flows.json

CMD ["npm", "start"]`

docker-compose:
`version: "3.7"

services:
  node-red:
    container_name: node-red
    build: .
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    networks:
      - operate_zeebe_network
    external_links:
      - zeebe:zeebe
    volumes:
      - node-red-data
volumes:
  node-red-data:

networks:
  operate_zeebe_network:
    external: true`

package.json dependences:
`"dependencies": {
        "node-red": "1.0.6",
        "node-red-contrib-zeebe": "0.6.3",
        "node-red-contrib-aws": "0.5.0",
        "node-red-dashboard": "~2.22.1"
    },`

On exec 'docker-compose up --build'
Output:
`node-red    | 30 May 13:05:56 - [info] Node-RED version: v1.0.6
node-red    | 30 May 13:05:56 - [info] Node.js  version: v10.20.1
node-red    | 30 May 13:05:56 - [info] Linux 4.14.177-107.254.amzn1.x86_64 x64 LE
node-red    | 30 May 13:05:56 - [info] Loading palette nodes
node-red exited with code 0
`

Without node-red-contrib-zeebe, is successfull.

Tks,

**Comment by pedesen** [comment]
Could you please upgrade to node-red-contrib-zeebe v0.7.0 and try again? Feel free to reopen this issue when the problem persists.
